# Generated by Django 3.2.5 on 2021-08-05 23:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('labs', '0002_rename_answer_lab_answer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='lab_answer',
        ),
        migrations.DeleteModel(
            name='lab_question',
        ),
    ]
